#!/bin/sh
#
# Load modules related to TS-7100
#

umask 077

start() {
	printf "Loading modules for TS-7100 peripherals: "

	modprobe m25p80
	modprobe ads7846
	modprobe mtdblock
	modprobe wilc_spi
	modprobe vf610_adc
	modprobe spi_oc
	modprobe 8250_of
	modprobe at25
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
